[project]
name = "wind-pilot"
version = "0.1.0"
description = "a pipeline + dashboard to analyze wind conditions at the Bourget Lake"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dbt-postgres>=1.11.0",
    "dlt[postgres]>=1.29.1",
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.51",
    "streamlit>=1.60.0",
]
